on: [push]

name: Deploy to Azure

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
      
    - uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Set up Deno
      uses: denolib/setup-deno@master
      with:
        deno-version: "1.2.3"

    - name: Bundle and zip Deno app
      run: |
        deno bundle server.ts server.bundle.js
        zip app.zip server.bundle.js

    - name: Deploy to Azure Web Apps
      uses: anthonychu/azure-webapps-deno-deploy@main
      with:
        app-name: test-deno-deploy
        resource-group: deno-webapp
        package: app.zip
        script-file: server.bundle.js
        deno-version: 1.2.3
