on: [push]

name: Deploy to Azure

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    - uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Set up Deno
      uses: denolib/setup-deno@master
      with:
        deno-version: 1.x

    - name: Bundle and zip Deno app
      run: |
        deno bundle server.ts server.bundle.js
        zip app.zip server.bundle.js

    # - name: Deploy to Azure Web Apps
    #   run: |
    #     az webapp config appsettings set -g deno-webapp -n deno-webapp --settings WEBSITES_ENABLE_APP_SERVICE_STORAGE=true WEBSITE_RUN_FROM_PACKAGE=1
    #     az webapp deployment source config-zip -g deno-webapp -n deno-webapp --src app.zip
    #     az webapp config container set --docker-custom-image-name anthonychu/deno:latest --docker-registry-server-url https://index.docker.io --name deno-webapp --resource-group deno-webapp
    #     az webapp config set -g deno-webapp -n deno-webapp --startup-file="deno run -A server.bundle.js"

    - name: Deploy to Azure Web Apps
      uses: anthonychu/azure-webapps-deno-deploy@master
      with:
        app-name: deno-webapp-action
        resource-group: deno-webapp
        package: app.zip
      env:
        test: 2
